import React, { createContext, useContext, useState, useEffect } from 'react';

// Translation data
const translations = {
  en: {
    // Common
    welcome: 'Welcome to BA Property Manager',
    subtitle: 'Smart property management platform in Buenos Aires',
    invited: 'Invited',
    accepted: 'Accepted',
    expired: 'Expired',
    status: 'Status',
    actions: 'Actions',
    user: 'User',
    myProfile: 'My Profile',
    signOut: 'Sign Out',
    personalInformation: 'Personal Information',
    edit: 'Edit',
    saving: 'Saving...',
    profileUpdatedSuccessfully: 'Profile updated successfully',
    errorUpdatingProfile: 'Error updating profile',
    login: 'Login',
    register: 'Register',
    logout: 'Logout',
    save: 'Save',
    cancel: 'Cancel',
    delete: 'Delete',
    add: 'Add',
    new: 'New',
    view: 'View',
    date: 'Date',
    name: 'Name',
    title: 'Title',
    email: 'Email',
    phone: 'Phone',
    address: 'Address',
    description: 'Description',
    loading: 'Loading...',
    error: 'Error',
    success: 'Success',
    pending: 'Pending',
    completed: 'Completed',
    rejected: 'Rejected',
    active: 'Active',
    inactive: 'Inactive',
    yes: 'Yes',
    no: 'No',
    close: 'Close',
    back: 'Back',
    next: 'Next',
    previous: 'Previous',
    submit: 'Submit',
    search: 'Search',
    filter: 'Filter',
    sort: 'Sort',
    refresh: 'Refresh',
    download: 'Download',
    upload: 'Upload',
    export: 'Export',
    import: 'Import',
    settings: 'Settings',
    profile: 'Profile',
    dashboard: 'Dashboard',
    overview: 'Overview',
    analytics: 'Analytics',
    reports: 'Reports',
    analyticsAndReports: 'Analytics and Reports',
    expensesByCategory: 'Expenses by Category',
    monthlyReport: 'Monthly Report',
    totalRequests: 'Total Requests',
    averageResponseTime: 'Average Response Time',
    average: 'Average',
    urgentResponse: 'Urgent',
    regularResponse: 'Regular',
    notifications: 'Notifications',
    help: 'Help',
    about: 'About',
    contact: 'Contact',
    privacy: 'Privacy',
    terms: 'Terms',
    language: 'Language',
    english: 'English',
    spanish: 'Spanish',
    
    // Navigation
    maintenance: 'Maintenance',
    community: 'Community',
    tenants: 'Tenants',
    invitations: 'Invitations',
    payments: 'Payments',
    
    // Dashboard
    totalApartments: 'Total Apartments',
    occupiedApartments: 'Occupied Apartments',
    vacantApartments: 'Vacant Apartments',
    maintenanceRequests: 'Maintenance Requests',
    pendingRequests: 'Pending Requests',
    completedRequests: 'Completed Requests',
    totalRevenue: 'Total Revenue',
    monthlyRevenue: 'Monthly Revenue',
    communityMembers: 'Community Members',
    activeMembers: 'Active Members',
    maintenanceCosts: 'Maintenance Costs',
    occupancyRate: 'Occupancy Rate',
    
    // Maintenance
    maintenanceManagement: 'Maintenance Management',
    newRequest: 'New Request',
    requestDetails: 'Request Details',
    newMaintenanceRequest: 'New Maintenance Request',
    request: 'Request',
    priority: 'Priority',
    high: 'High',
    medium: 'Medium',
    low: 'Low',
    category: 'Category',
    plumbing: 'Plumbing',
    electrical: 'Electrical',
    hvac: 'HVAC',
    cleaning: 'Cleaning',
    security: 'Security',
    other: 'Other',
    submittedBy: 'Submitted By',
    assignedTo: 'Assigned To',
    estimatedCost: 'Estimated Cost',
    actualCost: 'Actual Cost',
    timeSpent: 'Time Spent',
    vendor: 'Vendor',
    notes: 'Notes',
    updateStatus: 'Update Status',
    markComplete: 'Mark Complete',
    reopenRequest: 'Reopen Request',
    
    // Community
    newPost: 'New Post',
    postContent: 'Post Content',
    newCommunityPost: 'New Community Post',
    content: 'Content',
    shareWithCommunity: 'Share something with your community...',
    type: 'Type',
    question: 'Question',
    event: 'Event',
    appreciation: 'Appreciation',
    author: 'Author',
    apartment: 'Apartment',
    likes: 'Likes',
    comments: 'Comments',
    share: 'Share',
    report: 'Report',
    
    // Tenants
    tenantManagement: 'Tenant Management',
    newTenant: 'New Tenant',
    tenantDetails: 'Tenant Details',
    apartmentNumber: 'Apartment Number',
    leaseStart: 'Lease Start',
    leaseEnd: 'Lease End',
    rentAmount: 'Rent Amount',
    paymentStatus: 'Payment Status',
    contactInfo: 'Contact Info',
    emergencyContact: 'Emergency Contact',
    moveInDate: 'Move-in Date',
    moveOutDate: 'Move-out Date',
    
    // Invitations
    invitationManagement: 'Invitation Management',
    newInvitation: 'New Invitation',
    inviteNewTenant: 'Invite New Tenant',
    invitedBy: 'Invited By',
    invitationDate: 'Invitation Date',
    expiresAt: 'Expires At',
    resendInvitation: 'Resend Invitation',
    cancelInvitation: 'Cancel Invitation',
    invitationLink: 'Invitation Link',
    invitationEmailSent: 'An invitation email will be sent to complete registration',
    invitationEmailTemplate: 'Personalized message to include in the invitation email...',
    
    // Payments
    paymentManagement: 'Payment Management',
    newPayment: 'New Payment',
    paymentDetails: 'Payment Details',
    collectionRate: 'Collection Rate',
    amount: 'Amount',
    paymentDate: 'Payment Date',
    paymentMethod: 'Payment Method',
    cash: 'Cash',
    bankTransfer: 'Bank Transfer',
    creditCard: 'Credit Card',
    debitCard: 'Debit Card',
    check: 'Check',
    reference: 'Reference',
    receipt: 'Receipt',
    outstanding: 'Outstanding',
    paid: 'Paid',
    overdue: 'Overdue',
    
    // Authentication
    signIn: 'Sign In',
    signUp: 'Sign Up',
    forgotPassword: 'Forgot Password?',
    rememberMe: 'Remember Me',
    password: 'Password',
    confirmPassword: 'Confirm Password',
    currentPassword: 'Current Password',
    newPassword: 'New Password',
    userType: 'User Type',
    tenant: 'Tenant',
    propertyManager: 'Property Manager',
    buildingOwner: 'Building Owner',
    admin: 'Administrator',
    
    // Building
    buildingName: 'Building Name',
    buildingAddress: 'Building Address',
    buildingDescription: 'Building Description',
    buildingDetails: 'Building Details',
    joinBuilding: 'Join Building',
    buildingInvitation: 'Building Invitation',
    invitationToken: 'Invitation Token',
    
    // Messages
    welcomeMessage: 'Welcome to BA Property Manager',
    subtitleMessage: 'The complete platform to manage your building and connect with your community',
    loadingInvitation: 'Loading invitation...',
    invalidInvitationTitle: 'Invalid invitation',
    invitationExpired: 'Invitation expired',
    invitationExpiredMessage: 'This invitation has expired. Contact the building administrator for a new invitation.',
    errorLoadingInvitation: 'Error loading invitation',
    pleaseCompleteAllFields: 'Please complete all fields correctly',
    errorJoiningBuilding: 'Error joining building. Please try again.',
    completeRegistrationToAccess: 'Complete your registration to access your building',
    yourFullName: 'Your full name',
    rent: 'Rent',
    month: 'month',
    loginMessage: 'Sign in to your account',
    registerMessage: 'Create your account',
    noAccount: "Don't have an account?",
    haveAccount: 'Already have an account?',
    signUpHere: 'Sign up here',
    signInHere: 'Sign in here',
    profileUpdated: 'Profile updated successfully',
    invitationSent: 'Invitation sent successfully',
    invitationResent: 'Invitation resent successfully',
    invitationCancelled: 'Invitation cancelled successfully',
    requestSubmitted: 'Request submitted successfully',
    requestUpdated: 'Request updated successfully',
    paymentRecorded: 'Payment recorded successfully',
    postCreated: 'Post created successfully',
    invalidCredentials: 'Invalid email or password',
    emailExists: 'Email already exists',
    passwordsDontMatch: 'Passwords do not match',
    invalidInvitation: 'Invalid or expired invitation',
    buildingJoined: 'Successfully joined building',
    
    // Form validation
    required: 'This field is required',
    invalidEmail: 'Please enter a valid email address',
    fullName: 'Full Name',
    personalizedMessage: 'Personalized Message',
    optional: 'Optional',
    passwordTooShort: 'Password must be at least 6 characters',
    phoneInvalid: 'Please enter a valid phone number',
    apartmentRequired: 'Apartment number is required',
    buildingRequired: 'Building details are required',
    
    // Time
    today: 'Today',
    yesterday: 'Yesterday',
    thisWeek: 'This Week',
    thisMonth: 'This Month',
    lastMonth: 'Last Month',
    daysAgo: 'days ago',
    hoursAgo: 'hours ago',
    minutesAgo: 'minutes ago',
    justNow: 'Just now',
    
    // Currency
    currency: 'USD',
    currencySymbol: '$',
    
    // Building specific
    buenosAires: 'Buenos Aires',
    argentina: 'Argentina',
    neighborhood: 'Neighborhood',
    district: 'District',
    postalCode: 'Postal Code',
    buildingCode: 'Building Code',
    securityCode: 'Security Code',
    
    // Amenities
    amenities: 'Amenities',
    pool: 'Pool',
    gym: 'Gym',
    parking: 'Parking',
    elevator: 'Elevator',
    laundry: 'Laundry',
    wifi: 'WiFi',
    airConditioning: 'Air Conditioning',
    heating: 'Heating',
    balcony: 'Balcony',
    storage: 'Storage',
    
    // Maintenance categories
    emergency: 'Emergency',
    routine: 'Routine',
    preventive: 'Preventive',
    repair: 'Repair',
    replacement: 'Replacement',
    installation: 'Installation',
    inspection: 'Inspection',
    
    // Status colors
    statusPending: 'Pending',
    statusInProgress: 'In Progress',
    statusCompleted: 'Completed',
    statusCancelled: 'Cancelled',
    statusRejected: 'Rejected',
    
    // Dashboard sections
    recentRequests: 'Recent Requests',
    recentActivity: 'Recent Activity',
    
    // Additional keys
    memberSince: 'Member Since',
    accountType: 'Account Type',
    myBuilding: 'My Building',
    apartments: 'apartments',
    quickActions: 'Quick Actions',
    history: 'History',
    waterLeakDescription: 'There is a water leak in the bathroom of apartment 3A',
    inProgress: 'In Progress',
    method: 'Method',
    deposit: 'Deposit',
    expense: 'Expense',
    card: 'Card',
    additionalNotes: 'Additional notes...',
    monthlyRent: 'Monthly Rent',
    selectTenant: 'Select tenant',
    apartmentExample: 'Ex: 4C',
    emailExample: 'email@example.com',
    buildingNameExample: 'Ex: Central Building',
    buildingDescriptionPlaceholder: 'Describe the characteristics of your building...',
    enterRequestTitle: 'Enter request title',
    describeTheIssue: 'Describe the issue in detail',
    enterApartment: 'Enter apartment number',
    joining: 'Joining',
    termsAndConditions: 'By joining, you accept the building terms and conditions',
    
    // Priority levels
    priorityLow: 'Low',
    priorityMedium: 'Medium',
    priorityHigh: 'High',
    priorityUrgent: 'Urgent',
    urgent: 'Urgent',
    
    // User roles
    roleTenant: 'Tenant',
    rolePropertyManager: 'Property Manager',
    roleBuildingOwner: 'Building Owner',
    roleAdmin: 'Administrator',
    
    // Notifications
    notificationTitle: 'Notifications',
    noNotifications: 'No notifications',
    markAllRead: 'Mark all as read',
    notificationTypes: {
      maintenance: 'Maintenance Request',
      payment: 'Payment',
      community: 'Community Post',
      invitation: 'Invitation',
      general: 'General'
    },
    
    // Groups
    createGroup: 'Create Group',
    joinGroup: 'Join Group',
    leave: 'Leave',
    member: 'Member',
    members: 'members',
    posts: 'posts',
    viewPosts: 'View Posts',
    buildingGroup: 'Building Group',
    publicGroup: 'Public Group',
    privateGroup: 'Private Group',
    groupName: 'Group Name',
    groupDescription: 'Group Description',
    groupType: 'Group Type',
    selectGroupType: 'Select group type',
    communityPosts: 'Community Posts',
    noRecentActivity: 'No recent activity',
    recentPayments: 'Recent Payments',
    paid: 'Paid',
    pending: 'Pending',
    // Analytics and Reports
    lastWeek: 'Last Week',
    lastMonth: 'Last Month',
    lastQuarter: 'Last Quarter',
    lastYear: 'Last Year',
    exportReport: 'Export Report',
    exporting: 'Exporting...',
    maintenanceReport: 'Maintenance Report',
    financialReport: 'Financial Report',
    occupancyReport: 'Occupancy Report',
    comprehensiveReport: 'Comprehensive Report',
    maintenanceOverview: 'Maintenance Overview',
    maintenanceMetrics: 'Maintenance Metrics',
    highPriorityRequests: 'High Priority Requests',
    totalEstimatedCost: 'Total Estimated Cost',
    completionRate: 'Completion Rate',
    days: 'days',
    financialOverview: 'Financial Overview',
    totalRevenue: 'Total Revenue',
    pendingPayments: 'Pending Payments',
    rentPayments: 'Rent Payments',
    otherPayments: 'Other Payments',
    paymentBreakdown: 'Payment Breakdown',
    occupancyOverview: 'Occupancy Overview',
    occupiedUnits: 'Occupied Units',
    vacantUnits: 'Vacant Units',
    averageRent: 'Average Rent',
    tenantDistribution: 'Tenant Distribution',
    totalUnits: 'Total Units',
    buildingMetrics: 'Building Metrics',
    maintenanceSummary: 'Maintenance Summary',
    financialSummary: 'Financial Summary',
    totalCost: 'Total Cost',
    detailedData: 'Detailed Data',
    tenant: 'Tenant',
    amount: 'Amount',
    exportAsJSON: 'Export as JSON',
    exportAsCSV: 'Export as CSV'
  },
  es: {
    // Common
    welcome: 'Bienvenido a BA Property Manager',
    subtitle: 'Plataforma inteligente de gestión de propiedades en Buenos Aires',
    invited: 'Invitado',
    accepted: 'Aceptadas',
    expired: 'Expiradas',
    status: 'Estado',
    actions: 'Acciones',
    user: 'Usuario',
    myProfile: 'Mi Perfil',
    signOut: 'Cerrar Sesión',
    personalInformation: 'Información Personal',
    edit: 'Editar',
    saving: 'Guardando...',
    profileUpdatedSuccessfully: 'Perfil actualizado correctamente',
    errorUpdatingProfile: 'Error al actualizar el perfil',
    login: 'Iniciar Sesión',
    register: 'Registrarse',
    logout: 'Cerrar Sesión',
    save: 'Guardar',
    cancel: 'Cancelar',
    delete: 'Eliminar',
    add: 'Agregar',
    new: 'Nuevo',
    view: 'Ver',
    date: 'Fecha',
    name: 'Nombre',
    title: 'Título',
    email: 'Correo Electrónico',
    phone: 'Teléfono',
    address: 'Dirección',
    description: 'Descripción',
    loading: 'Cargando...',
    error: 'Error',
    success: 'Éxito',
    pending: 'Pendiente',
    completed: 'Completado',
    rejected: 'Rechazado',
    active: 'Activo',
    inactive: 'Inactivo',
    yes: 'Sí',
    no: 'No',
    close: 'Cerrar',
    back: 'Atrás',
    next: 'Siguiente',
    previous: 'Anterior',
    submit: 'Enviar',
    search: 'Buscar',
    filter: 'Filtrar',
    sort: 'Ordenar',
    refresh: 'Actualizar',
    download: 'Descargar',
    upload: 'Subir',
    export: 'Exportar',
    import: 'Importar',
    settings: 'Configuración',
    profile: 'Perfil',
    dashboard: 'Panel Principal',
    overview: 'Resumen',
    analytics: 'Analíticas',
    reports: 'Reportes',
    analyticsAndReports: 'Analíticas y Reportes',
    expensesByCategory: 'Gastos por Categoría',
    monthlyReport: 'Reporte Mensual',
    totalRequests: 'Solicitudes Totales',
    averageResponseTime: 'Tiempo de Respuesta Promedio',
    average: 'Promedio',
    urgentResponse: 'Urgente',
    regularResponse: 'Regular',
    notifications: 'Notificaciones',
    help: 'Ayuda',
    about: 'Acerca de',
    contact: 'Contacto',
    privacy: 'Privacidad',
    terms: 'Términos',
    language: 'Idioma',
    english: 'Inglés',
    spanish: 'Español',
    
    // Navigation
    maintenance: 'Mantenimiento',
    community: 'Comunidad',
    tenants: 'Inquilinos',
    invitations: 'Invitaciones',
    payments: 'Pagos',
    
    // Dashboard
    totalApartments: 'Total de Apartamentos',
    occupiedApartments: 'Apartamentos Ocupados',
    vacantApartments: 'Apartamentos Vacíos',
    maintenanceRequests: 'Solicitudes de Mantenimiento',
    pendingRequests: 'Solicitudes Pendientes',
    completedRequests: 'Solicitudes Completadas',
    totalRevenue: 'Ingresos Totales',
    monthlyRevenue: 'Ingresos Mensuales',
    communityMembers: 'Miembros de la Comunidad',
    activeMembers: 'Miembros Activos',
    maintenanceCosts: 'Costos de Mantenimiento',
    occupancyRate: 'Tasa de Ocupación',
    
    // Maintenance
    maintenanceManagement: 'Gestión de Mantenimiento',
    newRequest: 'Nueva Solicitud',
    requestDetails: 'Detalles de la Solicitud',
    newMaintenanceRequest: 'Nueva Solicitud de Mantenimiento',
    request: 'Solicitud',
    priority: 'Prioridad',
    high: 'Alta',
    medium: 'Media',
    low: 'Baja',
    category: 'Categoría',
    plumbing: 'Plomería',
    electrical: 'Eléctrico',
    hvac: 'Climatización',
    cleaning: 'Limpieza',
    security: 'Seguridad',
    other: 'Otro',
    submittedBy: 'Enviado Por',
    assignedTo: 'Asignado A',
    estimatedCost: 'Costo Estimado',
    actualCost: 'Costo Real',
    timeSpent: 'Tiempo Invertido',
    vendor: 'Proveedor',
    notes: 'Notas',
    updateStatus: 'Actualizar Estado',
    markComplete: 'Marcar como Completado',
    reopenRequest: 'Reabrir Solicitud',
    
    // Community
    newPost: 'Nuevo Post',
    postContent: 'Contenido del Post',
    newCommunityPost: 'Nuevo Post Comunitario',
    content: 'Contenido',
    shareWithCommunity: 'Comparte algo con tu comunidad...',
    type: 'Tipo',
    question: 'Pregunta',
    event: 'Evento',
    appreciation: 'Agradecimiento',
    author: 'Autor',
    apartment: 'Apartamento',
    likes: 'Me Gusta',
    comments: 'Comentarios',
    share: 'Compartir',
    report: 'Reportar',
    
    // Tenants
    tenantManagement: 'Gestión de Inquilinos',
    newTenant: 'Nuevo Inquilino',
    tenantDetails: 'Detalles del Inquilino',
    apartmentNumber: 'Número de Apartamento',
    leaseStart: 'Inicio de Alquiler',
    leaseEnd: 'Fin de Alquiler',
    rentAmount: 'Monto del Alquiler',
    paymentStatus: 'Estado de Pago',
    contactInfo: 'Información de Contacto',
    emergencyContact: 'Contacto de Emergencia',
    moveInDate: 'Fecha de Mudanza',
    moveOutDate: 'Fecha de Salida',
    
    // Invitations
    invitationManagement: 'Gestión de Invitaciones',
    newInvitation: 'Nueva Invitación',
    inviteNewTenant: 'Invitar Nuevo Inquilino',
    invitedBy: 'Invitado Por',
    invitationDate: 'Fecha de Invitación',
    expiresAt: 'Expira El',
    resendInvitation: 'Reenviar Invitación',
    cancelInvitation: 'Cancelar Invitación',
    invitationLink: 'Enlace de Invitación',
    invitationEmailSent: 'Se enviará un email de invitación para que complete su registro',
    invitationEmailTemplate: 'Mensaje personalizado para incluir en el email de invitación...',
    
    // Payments
    paymentManagement: 'Gestión de Pagos',
    newPayment: 'Nuevo Pago',
    paymentDetails: 'Detalles del Pago',
    collectionRate: 'Tasa de Cobro',
    amount: 'Monto',
    paymentDate: 'Fecha de Pago',
    paymentMethod: 'Método de Pago',
    cash: 'Efectivo',
    bankTransfer: 'Transferencia Bancaria',
    creditCard: 'Tarjeta de Crédito',
    debitCard: 'Tarjeta de Débito',
    check: 'Cheque',
    reference: 'Referencia',
    receipt: 'Recibo',
    outstanding: 'Pendiente',
    paid: 'Pagado',
    overdue: 'Vencido',
    
    // Authentication
    signIn: 'Iniciar Sesión',
    signUp: 'Registrarse',
    forgotPassword: '¿Olvidaste tu contraseña?',
    rememberMe: 'Recordarme',
    password: 'Contraseña',
    confirmPassword: 'Confirmar Contraseña',
    currentPassword: 'Contraseña Actual',
    newPassword: 'Nueva Contraseña',
    userType: 'Tipo de Usuario',
    tenant: 'Inquilino',
    propertyManager: 'Administrador de Propiedades',
    buildingOwner: 'Propietario del Edificio',
    admin: 'Administrador',
    
    // Building
    buildingName: 'Nombre del Edificio',
    buildingAddress: 'Dirección del Edificio',
    buildingDescription: 'Descripción del Edificio',
    buildingDetails: 'Detalles del Edificio',
    joinBuilding: 'Unirse al Edificio',
    buildingInvitation: 'Invitación al Edificio',
    invitationToken: 'Token de Invitación',
    
    // Messages
    welcomeMessage: 'Bienvenido a BA Property Manager',
    subtitleMessage: 'La plataforma completa para gestionar tu edificio y conectar con tu comunidad',
    loadingInvitation: 'Cargando invitación...',
    invalidInvitationTitle: 'Invitación no válida',
    invitationExpired: 'Invitación expirada',
    invitationExpiredMessage: 'Esta invitación ha expirado. Contacta al administrador del edificio para una nueva invitación.',
    errorLoadingInvitation: 'Error al cargar la invitación',
    pleaseCompleteAllFields: 'Por favor completa todos los campos correctamente',
    errorJoiningBuilding: 'Error al unirse al edificio. Inténtalo de nuevo.',
    completeRegistrationToAccess: 'Completa tu registro para acceder a tu edificio',
    yourFullName: 'Tu nombre completo',
    rent: 'Alquiler',
    month: 'mes',
    loginMessage: 'Inicia sesión en tu cuenta',
    registerMessage: 'Crea tu cuenta',
    noAccount: '¿No tienes cuenta?',
    haveAccount: '¿Ya tienes cuenta?',
    signUpHere: 'Regístrate aquí',
    signInHere: 'Inicia sesión aquí',
    profileUpdated: 'Perfil actualizado exitosamente',
    invitationSent: 'Invitación enviada exitosamente',
    invitationResent: 'Invitación reenviada exitosamente',
    invitationCancelled: 'Invitación cancelada exitosamente',
    requestSubmitted: 'Solicitud enviada exitosamente',
    requestUpdated: 'Solicitud actualizada exitosamente',
    paymentRecorded: 'Pago registrado exitosamente',
    postCreated: 'Post creado exitosamente',
    invalidCredentials: 'Correo o contraseña inválidos',
    emailExists: 'El correo ya existe',
    passwordsDontMatch: 'Las contraseñas no coinciden',
    invalidInvitation: 'Invitación inválida o expirada',
    buildingJoined: 'Te has unido exitosamente al edificio',
    
    // Form validation
    required: 'Este campo es requerido',
    invalidEmail: 'Por favor ingresa un correo válido',
    fullName: 'Nombre completo',
    personalizedMessage: 'Mensaje Personalizado',
    optional: 'Opcional',
    passwordTooShort: 'La contraseña debe tener al menos 6 caracteres',
    phoneInvalid: 'Por favor ingresa un número de teléfono válido',
    apartmentRequired: 'El número de apartamento es requerido',
    buildingRequired: 'Los detalles del edificio son requeridos',
    
    // Time
    today: 'Hoy',
    yesterday: 'Ayer',
    thisWeek: 'Esta Semana',
    thisMonth: 'Este Mes',
    lastMonth: 'Mes Pasado',
    daysAgo: 'días atrás',
    hoursAgo: 'horas atrás',
    minutesAgo: 'minutos atrás',
    justNow: 'Ahora mismo',
    
    // Currency
    currency: 'ARS',
    currencySymbol: '$',
    
    // Building specific
    buenosAires: 'Buenos Aires',
    argentina: 'Argentina',
    neighborhood: 'Barrio',
    district: 'Distrito',
    postalCode: 'Código Postal',
    buildingCode: 'Código del Edificio',
    securityCode: 'Código de Seguridad',
    
    // Amenities
    amenities: 'Amenities',
    pool: 'Piscina',
    gym: 'Gimnasio',
    parking: 'Estacionamiento',
    elevator: 'Ascensor',
    laundry: 'Lavandería',
    wifi: 'WiFi',
    airConditioning: 'Aire Acondicionado',
    heating: 'Calefacción',
    balcony: 'Balcón',
    storage: 'Depósito',
    
    // Maintenance categories
    emergency: 'Emergencia',
    routine: 'Rutina',
    preventive: 'Preventivo',
    repair: 'Reparación',
    replacement: 'Reemplazo',
    installation: 'Instalación',
    inspection: 'Inspección',
    
    // Status colors
    statusPending: 'Pendiente',
    statusInProgress: 'En Progreso',
    statusCompleted: 'Completado',
    statusCancelled: 'Cancelado',
    statusRejected: 'Rechazado',
    
    // Dashboard sections
    recentRequests: 'Solicitudes Recientes',
    recentActivity: 'Actividad Reciente',
    
    // Additional keys
    memberSince: 'Miembro desde',
    accountType: 'Tipo de Cuenta',
    myBuilding: 'Mi Edificio',
    apartments: 'apartamentos',
    quickActions: 'Acciones Rápidas',
    history: 'Historial',
    waterLeakDescription: 'Hay una fuga de agua en el baño del departamento 3A',
    inProgress: 'En Progreso',
    method: 'Método',
    deposit: 'Depósito',
    expense: 'Gasto',
    card: 'Tarjeta',
    additionalNotes: 'Notas adicionales...',
    monthlyRent: 'Alquiler Mensual',
    selectTenant: 'Seleccionar inquilino',
    apartmentExample: 'Ej: 4C',
    emailExample: 'email@ejemplo.com',
    buildingNameExample: 'Ej: Edificio Central',
    buildingDescriptionPlaceholder: 'Describe las características de tu edificio...',
    enterRequestTitle: 'Ingresa el título de la solicitud',
    describeTheIssue: 'Describe el problema en detalle',
    enterApartment: 'Ingresa el número de apartamento',
    joining: 'Uniéndose',
    termsAndConditions: 'Al unirte, aceptas los términos y condiciones del edificio',
    
    // Priority levels
    priorityLow: 'Baja',
    priorityMedium: 'Media',
    priorityHigh: 'Alta',
    priorityUrgent: 'Urgente',
    urgent: 'Crítica',
    
    // User roles
    roleTenant: 'Inquilino',
    rolePropertyManager: 'Administrador de Propiedades',
    roleBuildingOwner: 'Propietario del Edificio',
    roleAdmin: 'Administrador',
    
    // Notifications
    notificationTitle: 'Notificaciones',
    noNotifications: 'No hay notificaciones',
    markAllRead: 'Marcar todas como leídas',
    notificationTypes: {
      maintenance: 'Solicitud de Mantenimiento',
      payment: 'Pago',
      community: 'Post de Comunidad',
      invitation: 'Invitación',
      general: 'General'
    },
    
    // Groups
    createGroup: 'Crear Grupo',
    joinGroup: 'Unirse al Grupo',
    leave: 'Salir',
    member: 'Miembro',
    members: 'miembros',
    posts: 'posts',
    viewPosts: 'Ver Posts',
    buildingGroup: 'Grupo del Edificio',
    publicGroup: 'Grupo Público',
    privateGroup: 'Grupo Privado',
    groupName: 'Nombre del Grupo',
    groupDescription: 'Descripción del Grupo',
    groupType: 'Tipo de Grupo',
    selectGroupType: 'Seleccionar tipo de grupo',
    communityPosts: 'Posts de Comunidad',
    noRecentActivity: 'Sin actividad reciente',
    recentPayments: 'Pagos Recientes',
    paid: 'Pagado',
    pending: 'Pendiente',
    // Analytics and Reports
    lastWeek: 'Última Semana',
    lastMonth: 'Último Mes',
    lastQuarter: 'Último Trimestre',
    lastYear: 'Último Año',
    exportReport: 'Exportar Reporte',
    exporting: 'Exportando...',
    maintenanceReport: 'Reporte de Mantenimiento',
    financialReport: 'Reporte Financiero',
    occupancyReport: 'Reporte de Ocupación',
    comprehensiveReport: 'Reporte Integral',
    maintenanceOverview: 'Resumen de Mantenimiento',
    maintenanceMetrics: 'Métricas de Mantenimiento',
    highPriorityRequests: 'Solicitudes de Alta Prioridad',
    totalEstimatedCost: 'Costo Total Estimado',
    completionRate: 'Tasa de Finalización',
    days: 'días',
    financialOverview: 'Resumen Financiero',
    totalRevenue: 'Ingresos Totales',
    pendingPayments: 'Pagos Pendientes',
    rentPayments: 'Pagos de Alquiler',
    otherPayments: 'Otros Pagos',
    paymentBreakdown: 'Desglose de Pagos',
    occupancyOverview: 'Resumen de Ocupación',
    occupiedUnits: 'Unidades Ocupadas',
    vacantUnits: 'Unidades Vacías',
    averageRent: 'Alquiler Promedio',
    tenantDistribution: 'Distribución de Inquilinos',
    totalUnits: 'Total de Unidades',
    buildingMetrics: 'Métricas del Edificio',
    maintenanceSummary: 'Resumen de Mantenimiento',
    financialSummary: 'Resumen Financiero',
    totalCost: 'Costo Total',
    detailedData: 'Datos Detallados',
    tenant: 'Inquilino',
    amount: 'Monto',
    exportAsJSON: 'Exportar como JSON',
    exportAsCSV: 'Exportar como CSV'
  }
};

const LanguageContext = createContext();

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};

export const LanguageProvider = ({ children }) => {
  const [language, setLanguage] = useState(() => {
    // Get language from localStorage or default to Spanish
    const savedLanguage = localStorage.getItem('baPropertyManagerLanguage');
    return savedLanguage || 'es';
  });

  const t = (key) => {
    return translations[language][key] || key;
  };

  const changeLanguage = (newLanguage) => {
    setLanguage(newLanguage);
    localStorage.setItem('baPropertyManagerLanguage', newLanguage);
  };

  useEffect(() => {
    // Save language preference to localStorage whenever it changes
    localStorage.setItem('baPropertyManagerLanguage', language);
  }, [language]);

  const value = {
    language,
    changeLanguage,
    t,
    translations: translations[language]
  };

  return (
    <LanguageContext.Provider value={value}>
      {children}
    </LanguageContext.Provider>
  );
};
